ROILabels=table({'Scalp','Skull','CSF','WM','GM'}',(1:5)','VariableNames',{'ROI','Label'});

for i=1:54
	fn=sprintf('Brainweb_Subject%02d.mat',i);
	if(exist(fn,'file'))
		obj=load(fn);
                mesh=struct('x0x5F_DataInfo_',struct('JMeshVersion','0.5', 'Dimension',3, ...
                   'AnnotationFormat','https://github.com/NeuroJSON/jmesh/blob/master/JMesh_specification.md',...
                   'SerialFormat','http://json.org','Parser',struct('Python',["https://pypi.org/project/jdata","https://pypi.org/project/bjdata"],...
                   'MATLAB','https://github.com/NeuroJSON/jnifty','JavaScript','https://github.com/NeuroJSON/jsdata','CPP','https://github.com/NeuroJSON/json'),...
                   'BrainAtlasName', 'BrainWeb', 'BrainAtlasURL','https://brainweb.bic.mni.mcgill.ca/brainweb/',...
                   'BrainAtlasID',sprintf('Subject%02d',i), 'SegmentationDataVersion','Version 1','BrainROILabels',ROILabels,'Author','Fang Lab (http://fanglab.org)',...
                   'Date',datestr(now,29),'MeshGenerator','Brain2Mesh',...
                   'Contact','q.fang<at>neu.edu','CitationDOI','http://dx.doi.org/10.1117/1.NPh.7.1.015008','Citation',...
                   'Tran AP, Yan S, Fang Q, (2020) "Improving model-based fNIRS analysis using mesh-based anatomical and light-transport models," Neurophotonics 7(1), 015008'));
		mesh.MeshNode=obj.node;
		mesh.MeshElem=obj.elem;
                disp(i);
		tic;savejson('',mesh,'filename',sprintf('../BrainWeb_Subject%02d.jmsh',i),'compression','zlib');toc
	end
end