ROILabels=table({'Scalp','Skull','CSF','WM','GM'}',(1:5)','VariableNames',{'ROI','Label'});

fnames=dir('*.mat');
for i=1:length(fnames)
	fn=fnames(i);
        obj=load(fn.name);
        %obj.elem(obj.elem(:,end)<4,:)=[];
        [obj.node,obj.elem(:,1:4)]=removeisolatednode(obj.node,obj.elem(:,1:4));
        atlasid=regexprep(fn.name,'\.mat$','');
        mesh=struct('x0x5F_DataInfo_',struct('JMeshVersion','0.5', 'Dimension',3, ...
           'AnnotationFormat','https://github.com/NeuroJSON/jmesh/blob/master/JMesh_specification.md',...
           'SerialFormat','http://json.org','Parser',struct('Python',["https://pypi.org/project/jdata","https://pypi.org/project/bjdata"],...
           'MATLAB','https://github.com/NeuroJSON/jnifty','JavaScript','https://github.com/NeuroJSON/jsdata','CPP','https://github.com/NeuroJSON/json'),...
           'BrainAtlasName', 'Neurodevelopmental MRI Database', 'BrainAtlasURL','https://jerlab.sc.edu/projects/neurodevelopmental-mri-database',...
           'BrainAtlasID',atlasid, 'SegmentationDataVersion','Version 1','BrainROILabels',ROILabels,'Author','Fang Lab (http://fanglab.org)',...
           'Date',datestr(now,29),'MeshGenerator','Brain2Mesh',...
           'Contact','q.fang<at>neu.edu','CitationDOI','http://dx.doi.org/10.1117/1.NPh.7.1.015008','Citation',...
           'Tran AP, Yan S, Fang Q, (2020) "Improving model-based fNIRS analysis using mesh-based anatomical and light-transport models," Neurophotonics 7(1), 015008'));
        mesh.MeshNode=obj.node;
        mesh.MeshElem=obj.elem;
        disp(i);
        tic;savejson('',mesh,'filename',sprintf('../NDD_%s.jmsh',atlasid),'compression','zlib');toc
end